name: Haskell

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: haskell test
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install ghc -y
          sudo apt-get install cabal-install -y
      - name: build
        run: |
          cabal update
          cabal build all --only-dependencies --enable-tests --enable-benchmarks
      - name: test
        run: cabal test all
          
